### ISSUE TITLE
location field: more data returned from geocoder

### ISSUE THREAD

**Issue by fpurcell** [opentripplanner/otp-ui#13]
AltSource's comments:
![location-9](https://user-images.githubusercontent.com/64323/71685388-02be9e80-2d4d-11ea-9148-ddd609fb3f50.png)

Frank's $0.02 (see SEE #9 for more...):
We're going to need a geosearch form to only search on the 'stops' layers in Pelias.  
https://ws-st.trimet.org/pelias/v1/search?text=6&layers=stops

We're also going to need that form to return the stop_id and agency_id fields, which are encoded in the response via the id field -- e.g., {stop_id}:{agency_id}:{layer_name} is how the id field is composed in Pelias for transit (stops from GTFS).

SEE #9 for more...

**Comment by randolphjones** [comment]
To clarify, we could make more use of the model like this. We're fairly flexible on naming, etc. Just a suggestion for two new keys:

```
{
  lat,
  lon,
  name,
  stopId, //null or string
  type //string of 'STOP' or 'LOCATION'
}
```

At a glance, it looks like we can get by fine with adding `type` and `stopId` if the location is a stop. Let me know if any other clarification is needed. Thank you!
@fpurcell

**Comment by fpurcell** [comment]
At minimum, maybe return the **_id_** and **_type_** values from the underlying geocoder records.  In the Pelias case, this would mean returning a lot of necessary information, in that we'd get the layer name (e.g., 'stops'), the stop_id and agency_id.  The thinking here is that **_id_** and **_type_** fields are pretty generic, and should map to functionality in most geocoders, and the records therein.

Ala: the 'id' and 'layer' fields from Pelias for stop_id 111 are: "id": "111::TRIMET::stops", and "layer": "stops" for this query: http://cs-st-mapgeo01:4000/v1/autocomplete?text=111
