### ISSUE TITLE
Zip codes in geocoder results

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [opentripplanner/otp-ui#147]
From @fpurcell: in both MOD and this new CALL, the reverse geocoder is appending the zipcode to results (compare the popup vs. the pelias 'label').  Want to remove that, and just use the 'label' attribute returned from Pelias (wrapper).  (Also, if this is happening on MOD, it's old code (pre OTP-UI).

![image](https://user-images.githubusercontent.com/56846598/83446507-c6d35680-a41c-11ea-92a1-5ec3f93df554.png)

Notes: also need to apply in OTP-RR.

**Comment by binh-dam-ibigroup** [comment]
@fpurcell The OTP-ui library outputs the desired `label` property of the geocoder into `location.name` used by the `LocationField` component and other places in OTP-RR as of commit 855896d44d8eb71f348a3c485be0f05a8b39a20c.

In the illustration below, when you paste an address with the zip code,
the geocoder will suggest to you the same address without the zip code. When you click on the suggested address, the zip is not displayed in the location field.

![image](https://user-images.githubusercontent.com/56846598/84952764-82a0b100-b0c0-11ea-958d-93848aab9e95.png)

**Comment by fpurcell** [comment]
So strange.  I would swear this was an issue in OTP-UI.  Yet, I don't see it.  Close it.

**Comment by binh-dam-ibigroup** [comment]
Reopening this as I noticed zip codes were being added elsewhere, specifically when dragging markers on the map...

**Comment by fpurcell** [comment]
(I knew I saw this someplace in OTP-UI...good find, Binh)
