### ISSUE TITLE
base-map: change overlay layer's 'visible' prop when controlled via the layer switcher

### ISSUE THREAD

**Issue by fpurcell** [opentripplanner/otp-ui#16]
In otp-rr, the base-map's layer control updates the value of the 'visible' prop on added base layers.  Conversely, the otp-ui base-map component doesn't change said child components' 'visible' prop value from what was originally specified.  Would like otp-ui to mirror what otp-rr's layer switcher code does, and update the value of visible to either true/false, to thus reflect the state of the layer switcher for said layer.

This is important because the 'visible' prop, beyond setting the original state of which layers might be hidden / visible on app startup, is more importantly used used to turn on/off interval code and data updates.  With so many dynamic layers (e.g., e-scooters, bikes, rt vehicles), we only want the client doing fetch() work and updating leaflet layers when the layer is visible.

See these layers for use of visible to control the setInterval/clearInterval code:
 - https://github.com/opentripplanner/otp-react-redux/blob/dev/lib/components/map/zipcar-overlay.js#L44
 - https://github.com/opentripplanner/otp-react-redux/blob/dev/lib/components/map/vehicle-rental-overlay.js#L46

**Comment by binh-dam-ibigroup** [comment]
@fpurcell I think you are suggesting two separate modifications, is that correct?
1. The first one would be to rename the `visible` prop to `initiallyVisible` to indicate the initial state. I think that makes sense.
2. The other change is to capture and expose the event from the overlay selector, so that the parent component for BaseMap can update the state of the overlays?

**Comment by fpurcell** [comment]
Hey @binh-dam-ibigroup  ... no, just asking for #2 above, that the map set the prop value of visible to TRUE / FALSE based on layer switcher setting for that layer.  Like the name 'visible' all around, so not asking for a name change.

**Comment by binh-dam-ibigroup** [comment]
Hi @fpurcell, I would like to point out that, currently, the state of the overlays is [actually managed here](https://github.com/opentripplanner/otp-react-redux/blob/dev/lib/reducers/create-otp-reducer.js#L847).
In order for you to use componentDidUpdate as before, the equivalent code still needs to be built outside of BaseMap.

**Comment by landonreed** [comment]
Hi @fpurcell, we just wanted to follow up on this to see if we could close in favor of simply using the `onLayerAdded` and `onLayerRemoved`. Let us know if you/AltSource needs any more insights into our thinking here.

**Comment by fpurcell** [comment]
Hey @landonreed & @binh-dam-ibigroup & @evansiroky,

We've got 'dynamic' layers (e.g., setInterval enables data refresh fetch calls) in PR #23 https://tinyurl.com/t7duc8b (also have a tbd PR for vehicles https://tinyurl.com/upe5dda).   Such layers should only be fetching new data when said layer is visible on the map.  It's unclear to me how the clearInterval() will get called for said layer -- thoughts? 

Is the expectation that the app that implements base-map would then use the `onLayerAdded` and `onLayerRemoved` to call something on the vehicle layer to set/clear interval?  Or would the app send onLayerAdded/Removed down to the layers as props, to then control the set/clear interval?

**Comment by landonreed** [comment]
Our thought was that the app using base-map and the dynamic layers would, for example, use interactions with the user/elsewhere in the app to decide which overlays to show. When a layer is turned on, the expectation is that the overlay component would then mount, which is what triggers the `setInterval` data fetches in our layers. And similarly, when the app/user removes a layer, the overlay would unmount and clear the interval. The `onLayerAdded/Removed` is just a convenient way to callback when a layer is added/removed, so maybe that's not the approach AltSource will want to take, but it should be one valid approach. Does that track with your thinking?

**Comment by fpurcell** [comment]
Hey @landonreed  ...   yeah, I'm coming around to your way of thinking.  I'm going to slap together an app (or storybook) with a _container_ component that manages the map, and does what you're talking about.  Thus, I'm going to close this issue.

BTW, I believe every layer component performing `setInterval/clearInterval` will also need to look at changes to the 'visible' prop, and call `setInterval/clearInterval`.  The _container_ component mentioned above will manage the state of _visible_ for each layer it adds to the map, and that _visible_ prop will change via something I get out of `onLayerAdded/Removed` .  Correct me if I'm wrong, but we wouldn't want to tie `setInterval/clearInterval` just to the lifecycle of the component, since we'd want to see the layer available in the map's layer selector (so component is mounted), but we only want it fetching new data when the layer is being rendered on the map.  (This is esp. true for the RT vehicles layer I'm working on ... but really wouldn't want the e-scooter layers updating every minute or so either -- that is, unless they are in use atop the map).   Good?

**Comment by fpurcell** [comment]
Closing.  The new Vehicles #51 code uses Binh's code.
