### ISSUE TITLE
Itinerary Components Feedback from AltSource

### ISSUE THREAD

**Issue by PaulIvanov** [opentripplanner/otp-ui#18]
We primarily have styling feedback for items that we cant override using Styled-Components. There is stuff that is related to component ordering and actual content within the components. 
Most of the requests are also related to getting the view to look more like the UI mocks the Trimet marketing team provided for us. Let me know if you have any questions or comments, thanks. 

OTP UI Feedback:
- Change verbage on Transit Legs to have "Board" verb in it (Old: 52 Farmington/185th to Beaverton TC) (NEW: Board 52-Farmington/185th to Beaverton TC)
- Internals of "LegClickable" under the transit component causes centered multi-line styling.
- Allow for real-time arrival information to be passed into the itinerary body/Trip Legs.
- Change Trip Viewer Details info from "Ride 10 min / 15 stops" to "10-minute ride (15 stops)".
- Drop the "Service operated by Trimet" section on a transit leg. Or make it optional via a prop/config
- Add the service alerts section below the Trip viewer details section on a leg, instead of being on top.
- If The Service Alert section only has 1 alert, show it by default with a brief one-line display of the error.
- Some PropTypes could get some improvements. It was difficult to know what all the functions did and what they should take without diving into the actual library code.
- Is there a Handler for the "View leg on Map"/Map button on the right-side of the trip leg?

**Comment by PaulIvanov** [comment]
@fpurcell

**Comment by PaulIvanov** [comment]
The time stamp on the itinerary leg doesn't display the meridian. We dug into this and it looks like we are observing the time format set it the `timeOptions` object that is a prop of `ItineraryBody`; it conforms to this shape `{format: string}` OTP-UI does contain a module that contains the most complicated types, but we also pass in the timeFormat and dateFormat within the config. Should we be using the timeFormat from the config to at least allow us to override time options from the config? It's currently confusing which is the preferred way to get at the functionality we want.

**Comment by evansiroky** [comment]
Something that may still be needed is a custom renderer for the route name.
