### ISSUE TITLE
@opentripplanner/zoom-based-markers doesn't get resolved

### ISSUE THREAD

**Issue by atajadod** [opentripplanner/otp-ui#207]
Hi, 
I am trying to use the latest stops-overlay (with some changes to show agency name instead of id) and yarn install (npm install) can't find "@opentripplanner/zoom-based-markers".
Here is the package.json part
```json
"dependencies": {

    "@opentripplanner/zoom-based-markers": "^1.0.0"
  },
```
Thanks.

**Comment by evansiroky** [comment]
Whoops, looks like that never got published! Not sure why. It should be available now.
