### ISSUE TITLE
Failing PropType `leg.hailedCar` failing in PlaceRow

### ISSUE THREAD

**Issue by PaulIvanov** [opentripplanner/otp-ui#26]
Was receiving this failing propType and traced it down into OTP UI. The leg service has booleans for the property `leg.hailedCar`, which you can verify by looking at the mock data. 

Failed prop type: Invalid prop `leg.hailedCar` of type `boolean` supplied to `TriMetLegIcon`, expected `string`.
    in TriMetLegIcon (created by PlaceRow)
    in PlaceRow (created by ItineraryBody)

**Comment by evansiroky** [comment]
I'm not seeing any mocks where hailedCar is set to a non-boolean value, therefore I am unable to reproduce this.

**Comment by PaulIvanov** [comment]
I tried to reproduce this within the trimet.org project and I am no longer seeing it as an issue. Sorry about the long wait.
