### ISSUE TITLE
What version of OTP is the UI for?

### ISSUE THREAD

**Issue by Joey92** [opentripplanner/otp-ui#296]
Or is the otp-ui not really meant to be in sync with otp itself? I find some incompatibilities.

For e.g. I'm using the TransitiveOverlay for a Project of mine together with OTP 2.x. But it can't display the geometry of the trip because it's stiched together via the `interStopGeometry` on the itinerary leg which OTP does not provide. Same with a lot of other properties of the `legType` in core utils.

Other than that, great project! Really fell in love with it.

**Comment by fpurcell** [comment]
Hey Joey,

I believe most (if not all) OTP-UI development has been based on responses from OTP 1.x backends at this point.  @evansiroky dipped a toe into OTP 2.x, and might have gotten either OTP-UI or https://github.com/opentripplanner/otp-react-redux to limp along with an OTP 2.x itinerary responses.  

A move to OTP 2.x is on TriMet's long-term roadmap -- but our interest in that move is at least 9 months (mid 2022) away.

HTH,
Frank

**Comment by miles-grant-ibigroup** [comment]
Hey @Joey92 `core-utils` has now been updated to use `legGeometry` if `interStopGeometry`. Are there any other OTP-2 properties you're not seeing support for?

**Comment by fpurcell** [comment]
old - cleanup
