### ISSUE TITLE
Trip Form Settings Selector Panel feedback

### ISSUE THREAD

**Issue by PaulIvanov** [opentripplanner/otp-ui#46]
Hey All, just wanted to get these in front of you asap, so that they can get acknowledged when possible. Please Let me know if you need help reproducing any of the issues. Thanks!

Travel Preferences settings (ie "Optimize For/Walk Speed/Maximum Walk") with any mode of traveling is not functional. Receiving uncaught TypeError. This is visible in the OTP UI Storybook.

Trip Form/util.js line 156 is rendering an IconTag by doing a direct key lookup on line 148 which can come back null silently if the key doesnt exist.
The rendering will fail when a user tries to render that company Icon when the relevant mode is selected. 
We hit this issue when one our companies had all caps as the ID instead of the normal casing.

micromobilityModes array is req'd in the supportedModes prop even though Trimet doesnt support Micromobility only modes of traveling. Without it, `getBicycleOrMicromobilityModeOptions` throws a `TypeError: cannot read property 'map' of null

**Comment by PaulIvanov** [comment]
@fpurcell FYI

**Comment by fpurcell** [comment]
Can confirm Paul's bug:
![image](https://user-images.githubusercontent.com/64323/73110300-bb927c00-3eba-11ea-902d-f24161d27784.png)

**Comment by binh-dam-ibigroup** [comment]
Thanks for pointing this out, I neglected to address that in the original code.
