### ISSUE TITLE
Prop casing for transit-vehicles-overlay, itinerary

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [opentripplanner/otp-ui#52]
React props should be camelCased, however there are instance of PascalCased and alllowercased props in itinerary and transit-vehicles-overlay. This issue is to see whether/how to address them.

**Comment by evansiroky** [comment]
For some more context, the PascalCase props have been used as slot for custom components.

See https://github.com/opentripplanner/otp-ui/blob/c046416447367b6b66e060ad3b944e9ae8f70ba5/packages/itinerary-body/src/index.js#L157-L163

**Comment by fpurcell** [comment]
Cleanup...doesn't apply to latest rev of transit vehicle overlay.
