### ISSUE TITLE
New props for TransitVehicleOverlay component

### ISSUE THREAD

**Issue by randolphjones** [opentripplanner/otp-ui#58]
We will need a way to capture click events from the TransitVehicleOverlay component. When a user clicks a vehicle we will want to be able to invoke certain behavior in the app that is implementing the component. 

In order to get that done we will need something like an `onVehicleSelected` callback At the very least we will want the vehicle id supplied as an argument but we could also work with the full vehicle object. It's unclear if we will need access to the actual event from leaflet but at the moment it looks like that's not necessary.

We're wide open the details of the interface, naming, etc here so additional suggestions are welcome. 

Additionally when framing the selected vehicle in leaflet we will need to pass in an options object that handles the `paddingTopLeft` and `paddingBottomRight` properties seen here https://leafletjs.com/reference-1.6.0.html#fitbounds-options

In our app we're dynamically setting these properties for account a sidebar that is overlaid on the map when used on a desktop. Recentering of the map should account for this.

Thanks.

**Comment by fpurcell** [comment]
Hey @randolphjones  ... about the sidebar offset, here's what looks like the best option.  https://github.com/Leaflet/Leaflet/issues/859#issuecomment-26853083

I added this code to the vehicles component.  check out the dev version of storybook with added offset props:  https://opentransittools.github.io/otp-ui/?path=/story/realtime-vehiclelayer--real-time-vehicles-layer

**Comment by randolphjones** [comment]
@fpurcell Yeah, I worked with the knobs a little bit and have a pretty solid idea of what this is meant to do. I think this will work. If I understand correctly, the X/Y numbers we're providing as props here would be negative/positive depending on the direction? 

Within trip tools, we're dealing in the padding object but I think we can rework that to something broader within the hook we're using. I think it will just be a matter of remapping the data we're already computing for this.
