### ISSUE TITLE
Location-Field: SR-only text is shown when other error occurs.

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [opentripplanner/otp-ui#582]
I have one question about this behavior: 
<img width="962" alt="Screenshot 2023-05-12 at 11 10 22 AM" src="https://github.com/opentripplanner/otp-react-redux/assets/86619099/8efd0589-62a0-422a-abd1-aaa8ae330116">

It seems a bit strange to announce 3 places found but then not show them, but I'm not sure if that's related to this PR

_Originally posted by @miles-grant-ibigroup in https://github.com/opentripplanner/otp-react-redux/pull/892#pullrequestreview-1424721825_

**Comment by binh-dam-ibigroup** [comment]
@miles-grant-ibigroup If you have specific details on how you got that text to show, could you add them in this issue, please? Thank you.

**Comment by miles-grant-ibigroup** [comment]
To replicate: search for something, then select an item. Clicking on the location field and not hitting any key on the keyboard will trigger this confusing message
