### ISSUE TITLE
New Props for StopsOverlay Component

### ISSUE THREAD

**Issue by PaulIvanov** [opentripplanner/otp-ui#59]
Based on requirements for the new trimet.org project, we will need to be able to  support custom icons for stops. There are multiple styles such as a fully colored version, an opaque version, etc.. We think the best way to get this behavior is to provide a prop that lets us inject the marker object.

Currently there is no way to prevent the popup when clicking on a stop. We would like an optional prop to hide pop-ups on the overlay.

Currently there is no onClickHandler for the markIcon itself. We need this in order to tie into other functionality within the trimet app, and we would expect the stopId would be propogated up.

**Comment by PaulIvanov** [comment]
@fpurcell FYI

**Comment by fpurcell** [comment]
A few more thoughts:
 - Would also like to have different map icons for stops based on the 'mode' of the routes serving said stop.  Can use the modes (enum / strings) should be those defined in the GTFS spec.
- The trimet stop service (used in place of OTP's Transit Index) has an additional "mode" element:  https://newplanner.trimet.org/ws/ti/v0/index/stops?minLat=45.51&maxLat=45.52&minLon=-122.676&maxLon=-122.675
 - Where only one icon is passed into the component, that would be the overriding icon for all modes ...  maybe there's a default icon, and then modes could be specified on top of default icon.
- FWIW, history behind this is on ride.trimet.org, where we have different stop icons on the map for different modes.
