### ISSUE TITLE
Long press functionality in BaseMap component

### ISSUE THREAD

**Issue by randolphjones** [opentripplanner/otp-ui#64]
We have a request on the TORA project to implement long-press functionality in the app. The user will be using this for specifying a current location manually from the map instead of using geolocation API.  `onMapLongPress` prop added to basemap (or something equivalent, the name can be up to you). 

Alternately if you wanted to provide more granularity to the 'onMapClick' callback argument then we can handle things that way. We noticed that it passed an event name of `singleclick` so we can look at that event to switch behavior. This would keep your prop list a little shorter if you want.

Reach out if you have any questions or need any clarification. Thanks as always.

**Comment by fpurcell** [comment]
#70 addresses this issue
