### ISSUE TITLE
itinerary-body: time and route dot (styling issues)

### ISSUE THREAD

**Issue by fpurcell** [opentripplanner/otp-ui#95]
In the itinerary-body component, two styling issues jump out.

a) optional filter of long route names showing up in the dot:

For MAX and Streetcar routes, there's a truncated text in the route 'circle'.  Would like an component prop option to limit the size of text going into that circle (e.g., maybe a number, representing the max number of characters of the route name for it to render in the circle ... so our maxRouteNameLen <= 3) and thus filter the MA that's currently showing up:

![Screen Shot 2020-03-23 at 11 22 29 AM](https://user-images.githubusercontent.com/64323/77356956-8cef2100-6d04-11ea-9bb0-613eff2dc39a.png)

(Would rather just a red dot, than the partial string, and thus the MA above)

b) time alignment issues:

![Screen Shot 2020-03-23 at 11 14 29 AM](https://user-images.githubusercontent.com/64323/77357001-a2fce180-6d04-11ea-82e2-bdbd4ee6302a.png)

Both the vertical and horizontal alignment seen in the MOD app is also desired from the OTP-UI components. 

![Screen Shot 2020-03-23 at 11 26 45 AM](https://user-images.githubusercontent.com/64323/77357126-e0fa0580-6d04-11ea-8dff-bcaf6eff52eb.png)

Current alignment has a larger gutter to the right of the time on the horizontal, and the vertical is also a bit off (as seen in both the Storybook image above, and the top image from the new trimet.org app)

See #94 for other related itinerary-body changes.

**Comment by evansiroky** [comment]
Each of these two items seems to have ways to be resolved without changing any code.

- For the truncated text, there is a prop `toRouteAbbreviation` that can decide what to do with the route name.
- For the aligning of the times, one can do some custom styling of the  `TimeColumn` styled component.

**Comment by fpurcell** [comment]
Fixed (or demonstrated) via #97
